server:
  port: 7000

langchain4j:
  open-ai:
    #chat-model:
    streaming-chat-model:
      api-key: sk-11fe0a32df304d7f85d6fca4ea6ed9a0
      model-name: deepseek-chat #deepseek-reasoner 切换r1
      base-url: https://api.deepseek.com/v1
      log-requests: true
      log-responses: true


spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/chat_memory_demo
  application:
    name: lc4j-chat
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
#logging:
#  level:
#    root: debug

#logging.level.org.springframework: DEBUG
#logging.level.dev.langchain4j: TRACE
