server:
  port: 7100

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lc4j
    username: root
    password: 1206
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: lc4j-crud
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

#logging:
#  level:
#    root: debug

#logging.level.org.springframework: DEBUG
#logging.level.dev.langchain4j: TRACE